# Generated by Django 4.1.1 on 2022-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('localidad', models.TextField(max_length=50)),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=50)),
                ('categoria', models.TextField(max_length=20)),
                ('precio', models.FloatField()),
                ('espacio_en_disco', models.IntegerField()),
                ('fecha_alta', models.DateField()),
            ],
        ),
    ]
