# Generated by Django 4.1.1 on 2022-11-21 13:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=50)),
                ('categoria', models.TextField(max_length=20)),
                ('precio', models.FloatField()),
                ('espacio_en_disco', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.TextField(max_length=50)),
            ],
        ),
    ]
